# Generated by Django 2.2.2 on 2020-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='media/Map-Navigation.jpg', upload_to='media', verbose_name='картинка'),
        ),
    ]
